# Generated by Django 4.1.2 on 2022-10-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории меню',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Псевдоним')),
                ('composition', models.CharField(max_length=100, verbose_name='Состав млд.')),
                ('composition_ru', models.CharField(blank=True, max_length=100, verbose_name='Состав рус.')),
                ('volume_1', models.CharField(max_length=100, verbose_name='Объем/Вес')),
                ('price_1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('volume_2', models.CharField(blank=True, max_length=100, verbose_name='Объем/Вес')),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
