# Generated by Django 4.1.2 on 2022-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование рус.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование млд.'),
        ),
    ]
