# Generated by Django 4.1.2 on 2023-12-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/category_fotos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/category_icons', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='web.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Состав млд.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Состав рус.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование рус.'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Наименование'),
        ),
    ]
