# Generated by Django 4.1.2 on 2022-11-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='volume_1',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Объем/Вес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='volume_2',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Объем/Вес'),
            preserve_default=False,
        ),
    ]
