# Generated by Django 4.1.2 on 2022-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_item_name_ru_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_1',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_2',
            field=models.FloatField(blank=True, verbose_name='Цена'),
        ),
    ]
