# Generated by Django 4.1.2 on 2023-12-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_foto_category_icon_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_2',
        ),
    ]
