# Generated by Django 4.1.2 on 2022-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_item_volume_1_alter_item_volume_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='composition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Состав млд.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='composition_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Состав рус.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование рус.'),
        ),
    ]
