# Generated by Django 4.1.2 on 2022-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_item_composition_alter_item_composition_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='volume_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Объем/Вес'),
        ),
    ]
